export const TICKET_STATUSES = {
  RECEIVED: 'RECEIVED',
  OPEN: 'OPEN',
  IN_PROGRESS: 'IN_PROGRESS',
  RESOLVED: 'RESOLVED',
  REJECTED: 'REJECTED',
  CLOSED: 'CLOSED',
};
export const TICKET_STATUS = [
  TICKET_STATUSES.RECEIVED,
  TICKET_STATUSES.OPEN,
  TICKET_STATUSES.IN_PROGRESS,
  TICKET_STATUSES.RESOLVED,
  TICKET_STATUSES.REJECTED,
  TICKET_STATUSES.CLOSED,
];

export const TICKET_PRIORITY = ['Critical', 'High', 'Normal', 'Low'];

export const RIGHT_TICKET = 127000;
export const RIGHT_TICKET_SEARCH = 127000;
export const RIGHT_TICKET_ADD = 127001;
export const RIGHT_TICKET_EDIT = 127002;
export const RIGHT_TICKET_DELETE = 127003;
export const RIGHT_TICKET_VIEW_COMMENTS = 127004;
export const RIGHT_TICKET_ADD_COMMENT = 127005;
export const RIGHT_TICKET_RESOLVE = 127006;

export const MODULE_NAME = 'grievanceSocialProtection';
export const FETCH_INDIVIDUAL_REF = 'individual.actions.fetchIndividuals';

export const EMPTY_STRING = '';
export const GRIEVANT_TYPES = {
  INDIVIDUAL: 'individual',
  BENEFICIARY: 'beneficiary',
  USER: 'user',
};

export const GRIEVANT_TYPE_LIST = [GRIEVANT_TYPES.INDIVIDUAL, GRIEVANT_TYPES.USER];
export const GRIEVANCE_MAIN_MENU_CONTRIBUTION_KEY = 'grievance.MainMenu';

export const GRIEVANT_SEX = {
  MALE: 'M',
  FEMALE: 'F'
}

export const GRIEVANT_SEX_LIST = [
  GRIEVANT_SEX.MALE, GRIEVANT_SEX.FEMALE
]

export const DEFAULT = {
  IS_ADDITIONAL_PANEL_ENABLED: false,
  ALLOWED_DOMAINS_ATTACHMENTS: [],
  RENDER_LAST_NAME_FIRST: true,
};

// NULL - all tickets, 1 - with attachments, 2 - without attachments
export const ATTACHMENT_STATUS_WITH = 1;
export const ATTACHMENT_STATUS_WITHOUT = 2;
export const TICKET_ATTACHMENT_STATUS = [ATTACHMENT_STATUS_WITH, ATTACHMENT_STATUS_WITHOUT];

export const URL_TYPE_STRING = "URL";
export const FILE_TYPE_STRING = "FILE";
export const TICKET_ATTACHMENT_TYPE_STATUS = [URL_TYPE_STRING, FILE_TYPE_STRING];